// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task_Management_Api.Data;

#nullable disable

namespace Task_Management_Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Task_Management_Api.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "contact@techcorp.de",
                            Name = "TechCorp Solutions GmbH",
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            Email = "support@logisticsexpress.com",
                            Name = "Logistics Express AG",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "info@apexfinancial.com",
                            Name = "Apex Financial Group",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Task_Management_Api.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("taskItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            Description = "Perform a security and performance check on cloud servers.",
                            IsCompleted = false,
                            Status = 2,
                            Title = "System Infrastructure Audit"
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            Description = "Integrate shipment tracking API with the main dashboard.",
                            IsCompleted = true,
                            Status = 3,
                            Title = "API Integration Setup"
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 2,
                            Description = "Migrate legacy SQL database to PostgreSQL cluster.",
                            IsCompleted = false,
                            Status = 1,
                            Title = "Database Migration"
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 2,
                            Description = "Update dependencies and apply server patches.",
                            IsCompleted = false,
                            Status = 1,
                            Title = "Quarterly Maintenance"
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 3,
                            Description = "Implement export to PDF/Excel for monthly transactions.",
                            IsCompleted = true,
                            Status = 3,
                            Title = "Financial Report Module"
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 3,
                            Description = "Restrict access to sensitive financial records based on claims.",
                            IsCompleted = false,
                            Status = 2,
                            Title = "User Role Authorization"
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 3,
                            Description = "Test Stripe integration in sandbox environment.",
                            IsCompleted = false,
                            Status = 1,
                            Title = "Payment Gateway Testing"
                        },
                        new
                        {
                            Id = 8,
                            CustomerId = 3,
                            Description = "Conduct initial technical meeting for new portal usage.",
                            IsCompleted = true,
                            Status = 3,
                            Title = "Client Onboarding Review"
                        });
                });

            modelBuilder.Entity("Task_Management_Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@mail.com",
                            Name = "Admin",
                            Password = "admin",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "alex@mail.com",
                            Name = "Alex",
                            Password = "alex123",
                            Role = "User"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Ana@mail.com",
                            Name = "Ana",
                            Password = "ana123",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("Task_Management_Api.Models.Customer", b =>
                {
                    b.HasOne("Task_Management_Api.Models.User", "User")
                        .WithMany("customers")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Task_Management_Api.Models.TaskItem", b =>
                {
                    b.HasOne("Task_Management_Api.Models.Customer", "Customer")
                        .WithMany("Tasks")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Task_Management_Api.Models.Customer", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Task_Management_Api.Models.User", b =>
                {
                    b.Navigation("customers");
                });
#pragma warning restore 612, 618
        }
    }
}
